=== hmrc/pension-administrator/conf/resources/schemas/psaSubscription.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "04CC - API#1358 Pension Scheme Administrator Subscription- Request Schema",
  "type": "object",
  "properties": {
    "customerType": {
      "type": "string",
      "enum": [
        "UK",
        "NON-UK"
      ]
    },
    "legalStatus": {
      "type": "string",
      "enum": [
        "Individual",
        "Partnership",
        "Limited Company"
      ]
    },
    "idType": {
      "type": "string",
      "description": "For Individual - NINO, for Limited Company - UTR (CT UTR), for Partnership - UTR (SA UTR)",
      "enum": [
        "NINO",
        "UTR"
      ]
    },
    "idNumber": {
      "type": "string",
      "description": " NINO or UTR (CT UTR or SA UTR) value",
      "pattern": "^[A-Za-z0-9]{8,15}$"
    },
    "sapNumber" :{
      "type": "string",
      "description": " Identifier to get subscription id",
      "pattern": "^[A-Za-z0-9]{1,255}$"
    },
    "noIdentifier": {
      "description": "true for NON-UK customer and false for UK customer",
      "type": "boolean"
    },
    "organisationDetail": {
      "description": "Only required when legalStatus field is selected Limited Company",
      "$ref": "#/definitions/organisationDetailType"
    },
    "individualDetail": {
      "description ": "Only required when legalStatus field is selected Individual",
      "$ref": "#/definitions/individualDetailType"
    },
    "pensionSchemeAdministratoridentifierStatus": {
      "$ref": "#/definitions/pensionSchemeAdministratoridentifierStatusType"
    },
    "correspondenceAddressDetail": {
      "$ref": "#/definitions/addressType"
    },
    "correspondenceContactDetail": {
      "$ref": "#/definitions/contactDetailType"
    },
    "previousAddressDetail": {
      "$ref": "#/definitions/previousAddressDetailType"
    },
    "numberOfDirectorOrPartners": {
      "$ref": "#/definitions/numberOfDirectorOrPartnersType"
    },
    "directorOrPartnerDetail": {
      "$ref": "#/definitions/directorOrPartnerDetailType"
    },
    "declaration": {
      "$ref": "#/definitions/pensionSchemeAdministratorDeclarationType"
    }
  },
  "required": [
    "customerType",
    "legalStatus",
    "sapNumber" ,
    "noIdentifier",
    "pensionSchemeAdministratoridentifierStatus",
    "correspondenceAddressDetail",
    "correspondenceContactDetail",
    "previousAddressDetail",
    "declaration"
  ],
  "additionalProperties": false,
  "definitions": {
    "addressType": {
      "oneOf": [
        {
          "type": "object",
          "properties": {
            "addressType": {
              "type": "string",
              "enum": [
                "NON-UK"
              ]
            },
            "line1": {
              "$ref": "#/definitions/AddressLineType"
            },
            "line2": {
              "$ref": "#/definitions/AddressLineType"
            },
            "line3": {
              "$ref": "#/definitions/AddressLineType"
            },
            "line4": {
              "$ref": "#/definitions/AddressLineType"
            },
            "postalCode": {
              "description": "This is populated if the address supplied is a NON-UK address.",
              "type": "string",
              "minLength": 1,
              "maxLength": 10
            },
            "countryCode": {
              "$ref": "#/definitions/countryCodes"
            }
          },
          "required": [
            "addressType",
            "line1",
            "line2",
            "countryCode"
          ],
          "additionalProperties": false
        },
        {
          "type": "object",
          "properties": {
            "addressType": {
              "type": "string",
              "enum": [
                "UK"
              ]
            },
            "line1": {
              "$ref": "#/definitions/AddressLineType"
            },
            "line2": {
              "$ref": "#/definitions/AddressLineType"
            },
            "line3": {
              "$ref": "#/definitions/AddressLineType"
            },
            "line4": {
              "$ref": "#/definitions/AddressLineType"
            },
            "postalCode": {
              "description": "This is populated if the address supplied is a UK address.",
              "type": "string",
              "pattern": "^[A-Za-z]{1,2}[0-9][0-9A-Za-z]?\\s?[0-9][A-Za-z]{2}$"
            },
            "countryCode": {
              "$ref": "#/definitions/countryCodes"
            }
          },
          "required": [
            "addressType",
            "line1",
            "line2",
            "countryCode",
            "postalCode"
          ],
          "additionalProperties": false
        }
      ]
    },
    "AddressLineType": {
      "type": "string",
      "minLength": 1,
      "maxLength": 35,
      "pattern": "^[A-Za-z0-9 !'‘’\"“”(),./\u2014\u2013\u2010\u002d]{1,35}$"
    },
    "contactDetailType": {
      "type": "object",
      "properties": {
        "telephone": {
          "type": "string",
          "pattern": "^[0-9 ()+--]{1,24}$"
        },
        "mobileNumber": {
          "type": "string",
          "pattern": "^[0-9 ()+--]{1,24}$"
        },
        "fax": {
          "type": "string",
          "pattern": "^[0-9 ()+--]{1,24}$"
        },
        "email": {
          "type": "string",
          "maxLength": 132,
          "format": "email"
        }
      },
      "additionalProperties": false,
      "required": [
        "telephone",
        "email"
      ]
    },
    "organisationDetailType": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string",
          "pattern": "^[a-zA-Z0-9\u00C0-\u00FF !#$%&'‘’\"“”«»()*+,./:;=?@\\[\\]|~£€¥\\u005C\u2014\u2013\u2010\u005F\u005E\u0060\u002d]{1,160}$"
        },
        "crnNumber": {
          "type": "string",
          "pattern": "^[A-Za-z0-9 -]{7,8}$"
        },
        "vatRegistrationNumber": {
          "type": "string",
          "pattern": "^[0-9]{1,9}$"
        },
        "payeReference": {
          "type": "string",
          "pattern": "^[0-9]{3}[0-9A-Za-z]{1,13}$"
        }
      },
      "additionalProperties": false
    },
    "individualDetailType": {
      "type": "object",
      "properties": {
        "title": {
          "type": "string",
          "enum": [
            "Mr",
            "Mrs",
            "Miss",
            "Ms",
            "Dr",
            "Sir",
            "Professor",
            "Lord"
          ]
        },
        "firstName": {
          "type": "string",
          "pattern": "^[a-zA-Z &`\\-\\'\\.^]{1,35}$"
        },
        "middleName": {
          "type": "string",
          "pattern": "^[a-zA-Z &`\\-\\'\\.^]{1,35}$"
        },
        "lastName": {
          "type": "string",
          "pattern": "^[a-zA-Z &`\\-\\'\\.^]{1,35}$"
        },
        "dateOfBirth": {
          "type": "string",
          "pattern": "^(((19|20)([2468][048]|[13579][26]|0[48])|2000)[-]02[-]29|((19|20)[0-9]{2}[-](0[469]|11)[-](0[1-9]|1[0-9]|2[0-9]|30)|(19|20)[0-9]{2}[-](0[13578]|1[02])[-](0[1-9]|[12][0-9]|3[01])|(19|20)[0-9]{2}[-]02[-](0[1-9]|1[0-9]|2[0-8])))$"
        }
      },
      "additionalProperties": false,
      "required": [
        "firstName",
        "lastName",
        "dateOfBirth"
      ]
    },
    "pensionSchemeAdministratoridentifierStatusType": {
      "type": "object",
      "properties": {
        "isExistingPensionSchemaAdministrator": {
          "type": "boolean"
        },
        "existingPensionSchemaAdministratorReference": {
          "type": "string",
          "pattern": "^[a-zA-Z0-9]{8}$"
        }
      },
      "additionalProperties": false,
      "required": [
        "isExistingPensionSchemaAdministrator"
      ]
    },
    "previousAddressDetailType": {
      "type": "object",
      "properties": {
        "isPreviousAddressLast12Month": {
          "type": "boolean"
        },
        "previousAddressDetail": {
          "$ref": "#/definitions/addressType"
        }
      },
      "additionalProperties": false,
      "required": [
        "isPreviousAddressLast12Month"
      ]
    },
    "numberOfDirectorOrPartnersType": {
      "type": "object",
      "properties": {
        "isMorethanTenDirectors": {
          "type": "boolean"
        },
        "isMorethanTenPartners": {
          "type": "boolean"
        }
      },
      "additionalProperties": false
    },
    "directorOrPartnerDetailType": {
      "type": "array",
      "minItems": 0,
      "items": {
        "type": "object",
        "properties": {
          "sequenceId": {
            "type": "string",
            "pattern": "^[0-9]{3}$"
          },
          "entityType": {
            "type": "string",
            "enum": [
              "Director",
              "Partner"
            ]
          },
          "title": {
            "type": "string",
            "enum": [
              "Mr",
              "Mrs",
              "Miss",
              "Ms",
              "Dr",
              "Sir",
              "Professor",
              "Lord"
            ]
          },
          "firstName": {
            "type": "string",
            "pattern": "^[a-zA-Z &`\\-\\'\\.^]{1,35}$"
          },
          "middleName": {
            "type": "string",
            "pattern": "^[a-zA-Z &`\\-\\'\\.^]{1,35}$"
          },
          "lastName": {
            "type": "string",
            "pattern": "^[a-zA-Z &`\\-\\'\\.^]{1,35}$"
          },
          "dateOfBirth": {
            "type": "string",
            "pattern": "^(((19|20)([2468][048]|[13579][26]|0[48])|2000)[-]02[-]29|((19|20)[0-9]{2}[-](0[469]|11)[-](0[1-9]|1[0-9]|2[0-9]|30)|(19|20)[0-9]{2}[-](0[13578]|1[02])[-](0[1-9]|[12][0-9]|3[01])|(19|20)[0-9]{2}[-]02[-](0[1-9]|1[0-9]|2[0-8])))$"
          },
          "referenceOrNino": {
            "type": "string",
            "pattern": "(^[0-9a-zA-Z]{1,9}|((?!(BG|GB|KN|NK|NT|TN|ZZ)|(D|F|I|Q|U|V)[A-Z]|[A-Z](D|F|I|O|Q|U|V))[A-Z]{2})[0-9]{6}[A-D]?)$"
          },
          "noNinoReason": {
            "type": "string",
            "pattern": "^[a-zA-Z0-9\u00C0-\u00FF !#$%&'‘’\"“”«»()*+,./:;=?@\\[\\]|~£€¥\\u005C\u2014\u2013\u2010\u005F\u005E\u0060\u002d]{1,160}$"
          },
          "utr": {
            "type": "string",
            "pattern": "^[0-9]{10}$"
          },
          "noUtrReason": {
            "type": "string",
            "pattern": "^[a-zA-Z0-9\u00C0-\u00FF !#$%&'‘’\"“”«»()*+,./:;=?@\\[\\]|~£€¥\\u005C\u2014\u2013\u2010\u005F\u005E\u0060\u002d]{1,160}$"
          },
          "correspondenceCommonDetail": {
            "type": "object",
            "properties": {
              "addressDetail": {
                "$ref": "#/definitions/addressType"
              },
              "contactDetail": {
                "$ref": "#/definitions/contactDetailType"
              }
            },
            "additionalProperties": false,
            "required": [
              "addressDetail",
              "contactDetail"
            ]
          },
          "previousAddressDetail": {
            "$ref": "#/definitions/previousAddressDetailType"
          }
        },
        "additionalProperties": false,
        "required": [
          "sequenceId",
          "entityType",
          "firstName",
          "lastName",
          "dateOfBirth"
        ]
      }
    },
    "pensionSchemeAdministratorDeclarationType": {
      "type": "object",
      "properties": {
        "box1": {
          "type": "boolean"
        },
        "box2": {
          "type": "boolean"
        },
        "box3": {
          "type": "boolean"
        },
        "box4": {
          "type": "boolean"
        },
        "box5": {
          "type": "boolean"
        },
        "box6": {
          "type": "boolean"
        },
        "box7": {
          "type": "boolean"
        },
        "pensionAdvisorDetail": {
          "type": "object",
          "properties": {
            "name": {
              "type": "string",
              "pattern": "^[a-zA-Z &?*()\u005F\u00C0-\u00FF '‘’\u2014\u2013\u2010\u002d]{1,255}$"
            },
            "addressDetail": {
              "$ref": "#/definitions/addressType"
            },
            "contactDetail": {
              "$ref": "#/definitions/contactDetailType"
            }
          },
          "additionalProperties": false,
          "required": [
            "name",
            "addressDetail",
            "contactDetail"
          ]
        }
      },
      "additionalProperties": false,
      "required": [
        "box1",
        "box2",
        "box3",
        "box4",
        "box7"
      ]
    },
    "countryCodes": {
      "type": "string",
      "description": "Country code iso 3166-1 alpha-2",
      "enum": [
        "AD",
        "AE",
        "AF",
        "AG",
        "AI",
        "AL",
        "AM",
        "AN",
        "AO",
        "AQ",
        "AR",
        "AS",
        "AT",
        "AU",
        "AW",
        "AX",
        "AZ",
        "BA",
        "BB",
        "BD",
        "BE",
        "BF",
        "BG",
        "BH",
        "BI",
        "BJ",
        "BL",
        "BM",
        "BN",
        "BO",
        "BQ",
        "BR",
        "BS",
        "BT",
        "BV",
        "BW",
        "BY",
        "BZ",
        "CA",
        "CC",
        "CD",
        "CF",
        "CG",
        "CH",
        "CI",
        "CK",
        "CL",
        "CM",
        "CN",
        "CO",
        "CR",
        "CS",
        "CU",
        "CV",
        "CW",
        "CX",
        "CY",
        "CZ",
        "DE",
        "DJ",
        "DK",
        "DM",
        "DO",
        "DZ",
        "EC",
        "EE",
        "EG",
        "EH",
        "ER",
        "ES",
        "ET",
        "EU",
        "FI",
        "FJ",
        "FK",
        "FM",
        "FO",
        "FR",
        "GA",
        "GB",
        "GD",
        "GE",
        "GF",
        "GG",
        "GH",
        "GI",
        "GL",
        "GM",
        "GN",
        "GP",
        "GQ",
        "GR",
        "GS",
        "GT",
        "GU",
        "GW",
        "GY",
        "HK",
        "HM",
        "HN",
        "HR",
        "HT",
        "HU",
        "ID",
        "IE",
        "IL",
        "IM",
        "IN",
        "IO",
        "IQ",
        "IR",
        "IS",
        "IT",
        "JE",
        "JM",
        "JO",
        "JP",
        "KE",
        "KG",
        "KH",
        "KI",
        "KM",
        "KN",
        "KP",
        "KR",
        "KW",
        "KY",
        "KZ",
        "LA",
        "LB",
        "LC",
        "LI",
        "LK",
        "LR",
        "LS",
        "LT",
        "LU",
        "LV",
        "LY",
        "MA",
        "MC",
        "MD",
        "ME",
        "MF",
        "MG",
        "MH",
        "MK",
        "ML",
        "MM",
        "MN",
        "MO",
        "MP",
        "MQ",
        "MR",
        "MS",
        "MT",
        "MU",
        "MV",
        "MW",
        "MX",
        "MY",
        "MZ",
        "NA",
        "NC",
        "NE",
        "NF",
        "NG",
        "NI",
        "NL",
        "NO",
        "NP",
        "NR",
        "NT",
        "NU",
        "NZ",
        "OM",
        "PA",
        "PE",
        "PF",
        "PG",
        "PH",
        "PK",
        "PL",
        "PM",
        "PN",
        "PR",
        "PS",
        "PT",
        "PW",
        "PY",
        "QA",
        "RE",
        "RO",
        "RS",
        "RU",
        "RW",
        "SA",
        "SB",
        "SC",
        "SD",
        "SE",
        "SG",
        "SH",
        "SI",
        "SJ",
        "SK",
        "SL",
        "SM",
        "SN",
        "SO",
        "SR",
        "SS",
        "ST",
        "SV",
        "SX",
        "SY",
        "SZ",
        "TC",
        "TD",
        "TF",
        "TG",
        "TH",
        "TJ",
        "TK",
        "TL",
        "TM",
        "TN",
        "TO",
        "TP",
        "TR",
        "TT",
        "TV",
        "TW",
        "TZ",
        "UA",
        "UG",
        "UM",
        "UN",
        "US",
        "UY",
        "UZ",
        "VA",
        "VC",
        "VE",
        "VG",
        "VI",
        "VN",
        "VU",
        "WF",
        "WS",
        "YE",
        "YT",
        "ZA",
        "ZM",
        "ZW"
      ]
    }
  }
}

=== hmrc/pension-administrator/test/resources/data/psaRequestSample.json
{
  "customerType":"UK",
  "legalStatus":"Individual",
  "idType":"NINO",
  "idNumber":"AA999999A",
  "sapNumber":"0123456789",
  "noIdentifier":false,
  "individualDetail":{
    "title":"Mr",
    "firstName":"abcdefghijklmnopqrs",
    "middleName":"abcdefghijklmnopq",
    "lastName":"abcdefghijk",
    "dateOfBirth":"2018-12-12"
  },
  "pensionSchemeAdministratoridentifierStatus":{
    "isExistingPensionSchemaAdministrator":false,
    "existingPensionSchemaAdministratorReference":"01234567"
  },
  "correspondenceAddressDetail":{
    "addressType":"UK",
    "line1":"worthing 1",
    "line2":"worthing 2",
    "postalCode":"LN12 4DC",
    "countryCode":"GB"
  },
  "correspondenceContactDetail":{
    "telephone":"0044-09876542312",
    "mobileNumber":"0044-09876542312",
    "fax":"0044-09876542312",
    "email":"abc@hmrc.gsi.gov.uk"
  },
  "previousAddressDetail":{
    "isPreviousAddressLast12Month":true,
    "previousAddressDetail":{
      "addressType":"UK",
      "line1":"abcdefg",
      "line2":"abcdef",
      "line3":"abcd",
      "line4":"abcdefghijklmno",
      "postalCode":"B5 9EX",
      "countryCode":"GB"
    }
  },
  "numberOfDirectorOrPartners":{
    "isMorethanTenDirectors":true,
    "isMorethanTenPartners":true
  },
  "directorOrPartnerDetail":[
    {
      "sequenceId":"77",
      "entityType":"Director",
      "title":"Mr",
      "firstName":"abcdefghijklmnopqrs",
      "middleName":"abcdefg",
      "lastName":"abcdef",
      "dateOfBirth":"2018-12-12",
      "referenceOrNino":"AA999999A",
      "noNinoReason":"abcdefghijklmnopqrs",
      "utr":"0123456789",
      "noUtrReason":"abcdef",
      "correspondenceCommonDetail":{
        "addressDetail":{
          "addressType":"UK",
          "line1":"abcdefg",
          "line2":"abcdef",
          "line3":"abcd",
          "line4":"abcdefghijklmno",
          "postalCode":"B5 9EX",
          "countryCode":"GB"
        },
        "contactDetail":{
          "telephone":"0044-09876542312",
          "mobileNumber":"0044-09876542312",
          "fax":"0044-09876542312",
          "email":"abc@hmrc.gsi.gov.uk"
        }
      },
      "previousAddressDetail":{
        "isPreviousAddressLast12Month":false,
        "previousAddressDetail":{
          "addressType":"NON-UK",
          "line1":"abcdefg",
          "line2":"abcdef",
          "line3":"abcd",
          "line4":"abcdefghijklmno",
          "countryCode":"AD"
        }
      }
    }
  ],
  "declaration":{
    "box1":true,
    "box2":false,
    "box3":true,
    "box4":true,
    "box7":false
  }
}
